# Generated by Django 4.0.5 on 2022-07-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydata',
            options={'verbose_name_plural': 'Country Population Data'},
        ),
    ]
